const languages = {
  en: {
    name: "English",
    texts: [
      `EN1: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tincidunt id aliquet risus feugiat in ante metus. Vulputate eu scelerisque felis imperdiet proin. Blandit volutpat maecenas volutpat blandit aliquam etiam erat. Arcu non odio euismod lacinia. Rutrum quisque non tellus orci ac auctor. Aenean sed adipiscing diam donec adipiscing. Tristique magna sit amet purus gravida quis blandit turpis cursus. Orci porta non pulvinar neque laoreet suspendisse interdum. Sed odio morbi quis commodo odio aenean. Volutpat est velit egestas dui id ornare arcu. Diam vulputate ut pharetra sit. Diam quam nulla porttitor massa id neque. Vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Quis enim lobortis scelerisque fermentum dui faucibus. Eget arcu dictum varius duis at consectetur lorem donec. Tempor id eu nisl nunc mi ipsum faucibus vitae aliquet. Eget velit aliquet sagittis id. Auctor elit sed vulputate mi sit. Risus commodo viverra maecenas accumsan.

      Et magnis dis parturient montes. Accumsan in nisl nisi scelerisque eu ultrices vitae auctor. Odio eu feugiat pretium nibh ipsum. Libero id faucibus nisl tincidunt eget nullam. Viverra nam libero justo laoreet sit amet cursus sit. Vel quam elementum pulvinar etiam. Bibendum neque egestas congue quisque egestas diam in. Purus in massa tempor nec. Ante metus dictum at tempor commodo ullamcorper a lacus. Nunc eget lorem dolor sed viverra ipsum nunc. Lectus urna duis convallis convallis. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Amet volutpat consequat mauris nunc congue nisi vitae. Tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus. Sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus. Sit amet volutpat consequat mauris nunc congue nisi. Sit amet venenatis urna cursus eget nunc. Sagittis nisl rhoncus mattis rhoncus urna neque viverra justo.
  
      Quis risus sed vulputate odio ut enim blandit volutpat maecenas. Eget mi proin sed libero enim sed faucibus. Sed euismod nisi porta lorem mollis aliquam. Suspendisse faucibus interdum posuere lorem ipsum. Aliquam ut porttitor leo a diam sollicitudin. Nibh venenatis cras sed felis eget. Neque laoreet suspendisse interdum consectetur libero id faucibus nisl tincidunt. Quam id leo in vitae turpis massa sed elementum. Magna eget est lorem ipsum dolor. Eu augue ut lectus arcu bibendum at varius. Lectus vestibulum mattis ullamcorper velit. Sed libero enim sed faucibus turpis in eu. Sed cras ornare arcu dui vivamus arcu felis bibendum. Amet dictum sit amet justo. Tempus urna et pharetra pharetra. A scelerisque purus semper eget duis at tellus at urna.
  
      Mattis molestie a iaculis at erat pellentesque adipiscing commodo. Vel risus commodo viverra maecenas accumsan lacus vel facilisis volutpat. Sagittis vitae et leo duis ut diam quam nulla porttitor. Egestas egestas fringilla phasellus faucibus scelerisque eleifend donec. Iaculis urna id volutpat lacus. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Nunc faucibus a pellentesque sit amet porttitor eget dolor. Eget mauris pharetra et ultrices neque ornare aenean. Dui ut ornare lectus sit. Ac feugiat sed lectus vestibulum mattis ullamcorper velit sed. Faucibus ornare suspendisse sed nisi lacus sed viverra. Arcu dui vivamus arcu felis bibendum ut tristique. Amet commodo nulla facilisi nullam vehicula ipsum a arcu. Convallis aenean et tortor at risus. Elementum nibh tellus molestie nunc non. Interdum posuere lorem ipsum dolor sit. Varius duis at consectetur lorem donec massa sapien faucibus.
  
      Congue nisi vitae suscipit tellus mauris a diam maecenas. A erat nam at lectus. Eget egestas purus viverra accumsan in. Ac auctor augue mauris augue neque gravida. Sed viverra ipsum nunc aliquet bibendum enim. Proin libero nunc consequat interdum varius sit. Dictumst quisque sagittis purus sit. Bibendum arcu vitae elementum curabitur. In hac habitasse platea dictumst. Accumsan tortor posuere ac ut consequat semper viverra nam libero. Mauris in aliquam sem fringilla ut morbi tincidunt. Vel eros donec ac odio. Enim ut sem viverra aliquet. Scelerisque viverra mauris in aliquam sem fringilla ut. Arcu bibendum at varius vel pharetra. Aliquam etiam erat velit scelerisque in dictum.`,
      `EN2: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tincidunt id aliquet risus feugiat in ante metus. Vulputate eu scelerisque felis imperdiet proin. Blandit volutpat maecenas volutpat blandit aliquam etiam erat. Arcu non odio euismod lacinia. Rutrum quisque non tellus orci ac auctor. Aenean sed adipiscing diam donec adipiscing. Tristique magna sit amet purus gravida quis blandit turpis cursus. Orci porta non pulvinar neque laoreet suspendisse interdum. Sed odio morbi quis commodo odio aenean. Volutpat est velit egestas dui id ornare arcu. Diam vulputate ut pharetra sit. Diam quam nulla porttitor massa id neque. Vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Quis enim lobortis scelerisque fermentum dui faucibus. Eget arcu dictum varius duis at consectetur lorem donec. Tempor id eu nisl nunc mi ipsum faucibus vitae aliquet. Eget velit aliquet sagittis id. Auctor elit sed vulputate mi sit. Risus commodo viverra maecenas accumsan.

      Et magnis dis parturient montes. Accumsan in nisl nisi scelerisque eu ultrices vitae auctor. Odio eu feugiat pretium nibh ipsum. Libero id faucibus nisl tincidunt eget nullam. Viverra nam libero justo laoreet sit amet cursus sit. Vel quam elementum pulvinar etiam. Bibendum neque egestas congue quisque egestas diam in. Purus in massa tempor nec. Ante metus dictum at tempor commodo ullamcorper a lacus. Nunc eget lorem dolor sed viverra ipsum nunc. Lectus urna duis convallis convallis. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Amet volutpat consequat mauris nunc congue nisi vitae. Tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus. Sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus. Sit amet volutpat consequat mauris nunc congue nisi. Sit amet venenatis urna cursus eget nunc. Sagittis nisl rhoncus mattis rhoncus urna neque viverra justo.
      
      Quis risus sed vulputate odio ut enim blandit volutpat maecenas. Eget mi proin sed libero enim sed faucibus. Sed euismod nisi porta lorem mollis aliquam. Suspendisse faucibus interdum posuere lorem ipsum. Aliquam ut porttitor leo a diam sollicitudin. Nibh venenatis cras sed felis eget. Neque laoreet suspendisse interdum consectetur libero id faucibus nisl tincidunt. Quam id leo in vitae turpis massa sed elementum. Magna eget est lorem ipsum dolor. Eu augue ut lectus arcu bibendum at varius. Lectus vestibulum mattis ullamcorper velit. Sed libero enim sed faucibus turpis in eu. Sed cras ornare arcu dui vivamus arcu felis bibendum. Amet dictum sit amet justo. Tempus urna et pharetra pharetra. A scelerisque purus semper eget duis at tellus at urna.
      
      Mattis molestie a iaculis at erat pellentesque adipiscing commodo. Vel risus commodo viverra maecenas accumsan lacus vel facilisis volutpat. Sagittis vitae et leo duis ut diam quam nulla porttitor. Egestas egestas fringilla phasellus faucibus scelerisque eleifend donec. Iaculis urna id volutpat lacus. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Nunc faucibus a pellentesque sit amet porttitor eget dolor. Eget mauris pharetra et ultrices neque ornare aenean. Dui ut ornare lectus sit. Ac feugiat sed lectus vestibulum mattis ullamcorper velit sed. Faucibus ornare suspendisse sed nisi lacus sed viverra. Arcu dui vivamus arcu felis bibendum ut tristique. Amet commodo nulla facilisi nullam vehicula ipsum a arcu. Convallis aenean et tortor at risus. Elementum nibh tellus molestie nunc non. Interdum posuere lorem ipsum dolor sit. Varius duis at consectetur lorem donec massa sapien faucibus.
      
      Congue nisi vitae suscipit tellus mauris a diam maecenas. A erat nam at lectus. Eget egestas purus viverra accumsan in. Ac auctor augue mauris augue neque gravida. Sed viverra ipsum nunc aliquet bibendum enim. Proin libero nunc consequat interdum varius sit. Dictumst quisque sagittis purus sit. Bibendum arcu vitae elementum curabitur. In hac habitasse platea dictumst. Accumsan tortor posuere ac ut consequat semper viverra nam libero. Mauris in aliquam sem fringilla ut morbi tincidunt. Vel eros donec ac odio. Enim ut sem viverra aliquet. Scelerisque viverra mauris in aliquam sem fringilla ut. Arcu bibendum at varius vel pharetra. Aliquam etiam erat velit scelerisque in dictum.`,
      `EN3: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tincidunt id aliquet risus feugiat in ante metus. Vulputate eu scelerisque felis imperdiet proin. Blandit volutpat maecenas volutpat blandit aliquam etiam erat. Arcu non odio euismod lacinia. Rutrum quisque non tellus orci ac auctor. Aenean sed adipiscing diam donec adipiscing. Tristique magna sit amet purus gravida quis blandit turpis cursus. Orci porta non pulvinar neque laoreet suspendisse interdum. Sed odio morbi quis commodo odio aenean. Volutpat est velit egestas dui id ornare arcu. Diam vulputate ut pharetra sit. Diam quam nulla porttitor massa id neque. Vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Quis enim lobortis scelerisque fermentum dui faucibus. Eget arcu dictum varius duis at consectetur lorem donec. Tempor id eu nisl nunc mi ipsum faucibus vitae aliquet. Eget velit aliquet sagittis id. Auctor elit sed vulputate mi sit. Risus commodo viverra maecenas accumsan.

      Et magnis dis parturient montes. Accumsan in nisl nisi scelerisque eu ultrices vitae auctor. Odio eu feugiat pretium nibh ipsum. Libero id faucibus nisl tincidunt eget nullam. Viverra nam libero justo laoreet sit amet cursus sit. Vel quam elementum pulvinar etiam. Bibendum neque egestas congue quisque egestas diam in. Purus in massa tempor nec. Ante metus dictum at tempor commodo ullamcorper a lacus. Nunc eget lorem dolor sed viverra ipsum nunc. Lectus urna duis convallis convallis. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Amet volutpat consequat mauris nunc congue nisi vitae. Tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus. Sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus. Sit amet volutpat consequat mauris nunc congue nisi. Sit amet venenatis urna cursus eget nunc. Sagittis nisl rhoncus mattis rhoncus urna neque viverra justo.
      
      Quis risus sed vulputate odio ut enim blandit volutpat maecenas. Eget mi proin sed libero enim sed faucibus. Sed euismod nisi porta lorem mollis aliquam. Suspendisse faucibus interdum posuere lorem ipsum. Aliquam ut porttitor leo a diam sollicitudin. Nibh venenatis cras sed felis eget. Neque laoreet suspendisse interdum consectetur libero id faucibus nisl tincidunt. Quam id leo in vitae turpis massa sed elementum. Magna eget est lorem ipsum dolor. Eu augue ut lectus arcu bibendum at varius. Lectus vestibulum mattis ullamcorper velit. Sed libero enim sed faucibus turpis in eu. Sed cras ornare arcu dui vivamus arcu felis bibendum. Amet dictum sit amet justo. Tempus urna et pharetra pharetra. A scelerisque purus semper eget duis at tellus at urna.
      
      Mattis molestie a iaculis at erat pellentesque adipiscing commodo. Vel risus commodo viverra maecenas accumsan lacus vel facilisis volutpat. Sagittis vitae et leo duis ut diam quam nulla porttitor. Egestas egestas fringilla phasellus faucibus scelerisque eleifend donec. Iaculis urna id volutpat lacus. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Nunc faucibus a pellentesque sit amet porttitor eget dolor. Eget mauris pharetra et ultrices neque ornare aenean. Dui ut ornare lectus sit. Ac feugiat sed lectus vestibulum mattis ullamcorper velit sed. Faucibus ornare suspendisse sed nisi lacus sed viverra. Arcu dui vivamus arcu felis bibendum ut tristique. Amet commodo nulla facilisi nullam vehicula ipsum a arcu. Convallis aenean et tortor at risus. Elementum nibh tellus molestie nunc non. Interdum posuere lorem ipsum dolor sit. Varius duis at consectetur lorem donec massa sapien faucibus.
      
      Congue nisi vitae suscipit tellus mauris a diam maecenas. A erat nam at lectus. Eget egestas purus viverra accumsan in. Ac auctor augue mauris augue neque gravida. Sed viverra ipsum nunc aliquet bibendum enim. Proin libero nunc consequat interdum varius sit. Dictumst quisque sagittis purus sit. Bibendum arcu vitae elementum curabitur. In hac habitasse platea dictumst. Accumsan tortor posuere ac ut consequat semper viverra nam libero. Mauris in aliquam sem fringilla ut morbi tincidunt. Vel eros donec ac odio. Enim ut sem viverra aliquet. Scelerisque viverra mauris in aliquam sem fringilla ut. Arcu bibendum at varius vel pharetra. Aliquam etiam erat velit scelerisque in dictum.`,
      `EN4: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tincidunt id aliquet risus feugiat in ante metus. Vulputate eu scelerisque felis imperdiet proin. Blandit volutpat maecenas volutpat blandit aliquam etiam erat. Arcu non odio euismod lacinia. Rutrum quisque non tellus orci ac auctor. Aenean sed adipiscing diam donec adipiscing. Tristique magna sit amet purus gravida quis blandit turpis cursus. Orci porta non pulvinar neque laoreet suspendisse interdum. Sed odio morbi quis commodo odio aenean. Volutpat est velit egestas dui id ornare arcu. Diam vulputate ut pharetra sit. Diam quam nulla porttitor massa id neque. Vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Quis enim lobortis scelerisque fermentum dui faucibus. Eget arcu dictum varius duis at consectetur lorem donec. Tempor id eu nisl nunc mi ipsum faucibus vitae aliquet. Eget velit aliquet sagittis id. Auctor elit sed vulputate mi sit. Risus commodo viverra maecenas accumsan.

      Et magnis dis parturient montes. Accumsan in nisl nisi scelerisque eu ultrices vitae auctor. Odio eu feugiat pretium nibh ipsum. Libero id faucibus nisl tincidunt eget nullam. Viverra nam libero justo laoreet sit amet cursus sit. Vel quam elementum pulvinar etiam. Bibendum neque egestas congue quisque egestas diam in. Purus in massa tempor nec. Ante metus dictum at tempor commodo ullamcorper a lacus. Nunc eget lorem dolor sed viverra ipsum nunc. Lectus urna duis convallis convallis. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Amet volutpat consequat mauris nunc congue nisi vitae. Tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus. Sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus. Sit amet volutpat consequat mauris nunc congue nisi. Sit amet venenatis urna cursus eget nunc. Sagittis nisl rhoncus mattis rhoncus urna neque viverra justo.
      
      Quis risus sed vulputate odio ut enim blandit volutpat maecenas. Eget mi proin sed libero enim sed faucibus. Sed euismod nisi porta lorem mollis aliquam. Suspendisse faucibus interdum posuere lorem ipsum. Aliquam ut porttitor leo a diam sollicitudin. Nibh venenatis cras sed felis eget. Neque laoreet suspendisse interdum consectetur libero id faucibus nisl tincidunt. Quam id leo in vitae turpis massa sed elementum. Magna eget est lorem ipsum dolor. Eu augue ut lectus arcu bibendum at varius. Lectus vestibulum mattis ullamcorper velit. Sed libero enim sed faucibus turpis in eu. Sed cras ornare arcu dui vivamus arcu felis bibendum. Amet dictum sit amet justo. Tempus urna et pharetra pharetra. A scelerisque purus semper eget duis at tellus at urna.
      
      Mattis molestie a iaculis at erat pellentesque adipiscing commodo. Vel risus commodo viverra maecenas accumsan lacus vel facilisis volutpat. Sagittis vitae et leo duis ut diam quam nulla porttitor. Egestas egestas fringilla phasellus faucibus scelerisque eleifend donec. Iaculis urna id volutpat lacus. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Nunc faucibus a pellentesque sit amet porttitor eget dolor. Eget mauris pharetra et ultrices neque ornare aenean. Dui ut ornare lectus sit. Ac feugiat sed lectus vestibulum mattis ullamcorper velit sed. Faucibus ornare suspendisse sed nisi lacus sed viverra. Arcu dui vivamus arcu felis bibendum ut tristique. Amet commodo nulla facilisi nullam vehicula ipsum a arcu. Convallis aenean et tortor at risus. Elementum nibh tellus molestie nunc non. Interdum posuere lorem ipsum dolor sit. Varius duis at consectetur lorem donec massa sapien faucibus.
      
      Congue nisi vitae suscipit tellus mauris a diam maecenas. A erat nam at lectus. Eget egestas purus viverra accumsan in. Ac auctor augue mauris augue neque gravida. Sed viverra ipsum nunc aliquet bibendum enim. Proin libero nunc consequat interdum varius sit. Dictumst quisque sagittis purus sit. Bibendum arcu vitae elementum curabitur. In hac habitasse platea dictumst. Accumsan tortor posuere ac ut consequat semper viverra nam libero. Mauris in aliquam sem fringilla ut morbi tincidunt. Vel eros donec ac odio. Enim ut sem viverra aliquet. Scelerisque viverra mauris in aliquam sem fringilla ut. Arcu bibendum at varius vel pharetra. Aliquam etiam erat velit scelerisque in dictum.`,
    ],
  },
  fr: {
    name: "French",
    texts: [
      `FR1: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tincidunt id aliquet risus feugiat in ante metus. Vulputate eu scelerisque felis imperdiet proin. Blandit volutpat maecenas volutpat blandit aliquam etiam erat. Arcu non odio euismod lacinia. Rutrum quisque non tellus orci ac auctor. Aenean sed adipiscing diam donec adipiscing. Tristique magna sit amet purus gravida quis blandit turpis cursus. Orci porta non pulvinar neque laoreet suspendisse interdum. Sed odio morbi quis commodo odio aenean. Volutpat est velit egestas dui id ornare arcu. Diam vulputate ut pharetra sit. Diam quam nulla porttitor massa id neque. Vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Quis enim lobortis scelerisque fermentum dui faucibus. Eget arcu dictum varius duis at consectetur lorem donec. Tempor id eu nisl nunc mi ipsum faucibus vitae aliquet. Eget velit aliquet sagittis id. Auctor elit sed vulputate mi sit. Risus commodo viverra maecenas accumsan.

    Et magnis dis parturient montes. Accumsan in nisl nisi scelerisque eu ultrices vitae auctor. Odio eu feugiat pretium nibh ipsum. Libero id faucibus nisl tincidunt eget nullam. Viverra nam libero justo laoreet sit amet cursus sit. Vel quam elementum pulvinar etiam. Bibendum neque egestas congue quisque egestas diam in. Purus in massa tempor nec. Ante metus dictum at tempor commodo ullamcorper a lacus. Nunc eget lorem dolor sed viverra ipsum nunc. Lectus urna duis convallis convallis. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Amet volutpat consequat mauris nunc congue nisi vitae. Tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus. Sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus. Sit amet volutpat consequat mauris nunc congue nisi. Sit amet venenatis urna cursus eget nunc. Sagittis nisl rhoncus mattis rhoncus urna neque viverra justo.

    Quis risus sed vulputate odio ut enim blandit volutpat maecenas. Eget mi proin sed libero enim sed faucibus. Sed euismod nisi porta lorem mollis aliquam. Suspendisse faucibus interdum posuere lorem ipsum. Aliquam ut porttitor leo a diam sollicitudin. Nibh venenatis cras sed felis eget. Neque laoreet suspendisse interdum consectetur libero id faucibus nisl tincidunt. Quam id leo in vitae turpis massa sed elementum. Magna eget est lorem ipsum dolor. Eu augue ut lectus arcu bibendum at varius. Lectus vestibulum mattis ullamcorper velit. Sed libero enim sed faucibus turpis in eu. Sed cras ornare arcu dui vivamus arcu felis bibendum. Amet dictum sit amet justo. Tempus urna et pharetra pharetra. A scelerisque purus semper eget duis at tellus at urna.

    Mattis molestie a iaculis at erat pellentesque adipiscing commodo. Vel risus commodo viverra maecenas accumsan lacus vel facilisis volutpat. Sagittis vitae et leo duis ut diam quam nulla porttitor. Egestas egestas fringilla phasellus faucibus scelerisque eleifend donec. Iaculis urna id volutpat lacus. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Nunc faucibus a pellentesque sit amet porttitor eget dolor. Eget mauris pharetra et ultrices neque ornare aenean. Dui ut ornare lectus sit. Ac feugiat sed lectus vestibulum mattis ullamcorper velit sed. Faucibus ornare suspendisse sed nisi lacus sed viverra. Arcu dui vivamus arcu felis bibendum ut tristique. Amet commodo nulla facilisi nullam vehicula ipsum a arcu. Convallis aenean et tortor at risus. Elementum nibh tellus molestie nunc non. Interdum posuere lorem ipsum dolor sit. Varius duis at consectetur lorem donec massa sapien faucibus.

    Congue nisi vitae suscipit tellus mauris a diam maecenas. A erat nam at lectus. Eget egestas purus viverra accumsan in. Ac auctor augue mauris augue neque gravida. Sed viverra ipsum nunc aliquet bibendum enim. Proin libero nunc consequat interdum varius sit. Dictumst quisque sagittis purus sit. Bibendum arcu vitae elementum curabitur. In hac habitasse platea dictumst. Accumsan tortor posuere ac ut consequat semper viverra nam libero. Mauris in aliquam sem fringilla ut morbi tincidunt. Vel eros donec ac odio. Enim ut sem viverra aliquet. Scelerisque viverra mauris in aliquam sem fringilla ut. Arcu bibendum at varius vel pharetra. Aliquam etiam erat velit scelerisque in dictum.`,

      `FR2: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tincidunt id aliquet risus feugiat in ante metus. Vulputate eu scelerisque felis imperdiet proin. Blandit volutpat maecenas volutpat blandit aliquam etiam erat. Arcu non odio euismod lacinia. Rutrum quisque non tellus orci ac auctor. Aenean sed adipiscing diam donec adipiscing. Tristique magna sit amet purus gravida quis blandit turpis cursus. Orci porta non pulvinar neque laoreet suspendisse interdum. Sed odio morbi quis commodo odio aenean. Volutpat est velit egestas dui id ornare arcu. Diam vulputate ut pharetra sit. Diam quam nulla porttitor massa id neque. Vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Quis enim lobortis scelerisque fermentum dui faucibus. Eget arcu dictum varius duis at consectetur lorem donec. Tempor id eu nisl nunc mi ipsum faucibus vitae aliquet. Eget velit aliquet sagittis id. Auctor elit sed vulputate mi sit. Risus commodo viverra maecenas accumsan.

    Et magnis dis parturient montes. Accumsan in nisl nisi scelerisque eu ultrices vitae auctor. Odio eu feugiat pretium nibh ipsum. Libero id faucibus nisl tincidunt eget nullam. Viverra nam libero justo laoreet sit amet cursus sit. Vel quam elementum pulvinar etiam. Bibendum neque egestas congue quisque egestas diam in. Purus in massa tempor nec. Ante metus dictum at tempor commodo ullamcorper a lacus. Nunc eget lorem dolor sed viverra ipsum nunc. Lectus urna duis convallis convallis. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Amet volutpat consequat mauris nunc congue nisi vitae. Tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus. Sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus. Sit amet volutpat consequat mauris nunc congue nisi. Sit amet venenatis urna cursus eget nunc. Sagittis nisl rhoncus mattis rhoncus urna neque viverra justo.
    
    Quis risus sed vulputate odio ut enim blandit volutpat maecenas. Eget mi proin sed libero enim sed faucibus. Sed euismod nisi porta lorem mollis aliquam. Suspendisse faucibus interdum posuere lorem ipsum. Aliquam ut porttitor leo a diam sollicitudin. Nibh venenatis cras sed felis eget. Neque laoreet suspendisse interdum consectetur libero id faucibus nisl tincidunt. Quam id leo in vitae turpis massa sed elementum. Magna eget est lorem ipsum dolor. Eu augue ut lectus arcu bibendum at varius. Lectus vestibulum mattis ullamcorper velit. Sed libero enim sed faucibus turpis in eu. Sed cras ornare arcu dui vivamus arcu felis bibendum. Amet dictum sit amet justo. Tempus urna et pharetra pharetra. A scelerisque purus semper eget duis at tellus at urna.
    
    Mattis molestie a iaculis at erat pellentesque adipiscing commodo. Vel risus commodo viverra maecenas accumsan lacus vel facilisis volutpat. Sagittis vitae et leo duis ut diam quam nulla porttitor. Egestas egestas fringilla phasellus faucibus scelerisque eleifend donec. Iaculis urna id volutpat lacus. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Nunc faucibus a pellentesque sit amet porttitor eget dolor. Eget mauris pharetra et ultrices neque ornare aenean. Dui ut ornare lectus sit. Ac feugiat sed lectus vestibulum mattis ullamcorper velit sed. Faucibus ornare suspendisse sed nisi lacus sed viverra. Arcu dui vivamus arcu felis bibendum ut tristique. Amet commodo nulla facilisi nullam vehicula ipsum a arcu. Convallis aenean et tortor at risus. Elementum nibh tellus molestie nunc non. Interdum posuere lorem ipsum dolor sit. Varius duis at consectetur lorem donec massa sapien faucibus.
    
    Congue nisi vitae suscipit tellus mauris a diam maecenas. A erat nam at lectus. Eget egestas purus viverra accumsan in. Ac auctor augue mauris augue neque gravida. Sed viverra ipsum nunc aliquet bibendum enim. Proin libero nunc consequat interdum varius sit. Dictumst quisque sagittis purus sit. Bibendum arcu vitae elementum curabitur. In hac habitasse platea dictumst. Accumsan tortor posuere ac ut consequat semper viverra nam libero. Mauris in aliquam sem fringilla ut morbi tincidunt. Vel eros donec ac odio. Enim ut sem viverra aliquet. Scelerisque viverra mauris in aliquam sem fringilla ut. Arcu bibendum at varius vel pharetra. Aliquam etiam erat velit scelerisque in dictum.`,
      `FR3: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tincidunt id aliquet risus feugiat in ante metus. Vulputate eu scelerisque felis imperdiet proin. Blandit volutpat maecenas volutpat blandit aliquam etiam erat. Arcu non odio euismod lacinia. Rutrum quisque non tellus orci ac auctor. Aenean sed adipiscing diam donec adipiscing. Tristique magna sit amet purus gravida quis blandit turpis cursus. Orci porta non pulvinar neque laoreet suspendisse interdum. Sed odio morbi quis commodo odio aenean. Volutpat est velit egestas dui id ornare arcu. Diam vulputate ut pharetra sit. Diam quam nulla porttitor massa id neque. Vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Quis enim lobortis scelerisque fermentum dui faucibus. Eget arcu dictum varius duis at consectetur lorem donec. Tempor id eu nisl nunc mi ipsum faucibus vitae aliquet. Eget velit aliquet sagittis id. Auctor elit sed vulputate mi sit. Risus commodo viverra maecenas accumsan.

    Et magnis dis parturient montes. Accumsan in nisl nisi scelerisque eu ultrices vitae auctor. Odio eu feugiat pretium nibh ipsum. Libero id faucibus nisl tincidunt eget nullam. Viverra nam libero justo laoreet sit amet cursus sit. Vel quam elementum pulvinar etiam. Bibendum neque egestas congue quisque egestas diam in. Purus in massa tempor nec. Ante metus dictum at tempor commodo ullamcorper a lacus. Nunc eget lorem dolor sed viverra ipsum nunc. Lectus urna duis convallis convallis. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Amet volutpat consequat mauris nunc congue nisi vitae. Tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus. Sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus. Sit amet volutpat consequat mauris nunc congue nisi. Sit amet venenatis urna cursus eget nunc. Sagittis nisl rhoncus mattis rhoncus urna neque viverra justo.
    
    Quis risus sed vulputate odio ut enim blandit volutpat maecenas. Eget mi proin sed libero enim sed faucibus. Sed euismod nisi porta lorem mollis aliquam. Suspendisse faucibus interdum posuere lorem ipsum. Aliquam ut porttitor leo a diam sollicitudin. Nibh venenatis cras sed felis eget. Neque laoreet suspendisse interdum consectetur libero id faucibus nisl tincidunt. Quam id leo in vitae turpis massa sed elementum. Magna eget est lorem ipsum dolor. Eu augue ut lectus arcu bibendum at varius. Lectus vestibulum mattis ullamcorper velit. Sed libero enim sed faucibus turpis in eu. Sed cras ornare arcu dui vivamus arcu felis bibendum. Amet dictum sit amet justo. Tempus urna et pharetra pharetra. A scelerisque purus semper eget duis at tellus at urna.
    
    Mattis molestie a iaculis at erat pellentesque adipiscing commodo. Vel risus commodo viverra maecenas accumsan lacus vel facilisis volutpat. Sagittis vitae et leo duis ut diam quam nulla porttitor. Egestas egestas fringilla phasellus faucibus scelerisque eleifend donec. Iaculis urna id volutpat lacus. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Nunc faucibus a pellentesque sit amet porttitor eget dolor. Eget mauris pharetra et ultrices neque ornare aenean. Dui ut ornare lectus sit. Ac feugiat sed lectus vestibulum mattis ullamcorper velit sed. Faucibus ornare suspendisse sed nisi lacus sed viverra. Arcu dui vivamus arcu felis bibendum ut tristique. Amet commodo nulla facilisi nullam vehicula ipsum a arcu. Convallis aenean et tortor at risus. Elementum nibh tellus molestie nunc non. Interdum posuere lorem ipsum dolor sit. Varius duis at consectetur lorem donec massa sapien faucibus.
    
    Congue nisi vitae suscipit tellus mauris a diam maecenas. A erat nam at lectus. Eget egestas purus viverra accumsan in. Ac auctor augue mauris augue neque gravida. Sed viverra ipsum nunc aliquet bibendum enim. Proin libero nunc consequat interdum varius sit. Dictumst quisque sagittis purus sit. Bibendum arcu vitae elementum curabitur. In hac habitasse platea dictumst. Accumsan tortor posuere ac ut consequat semper viverra nam libero. Mauris in aliquam sem fringilla ut morbi tincidunt. Vel eros donec ac odio. Enim ut sem viverra aliquet. Scelerisque viverra mauris in aliquam sem fringilla ut. Arcu bibendum at varius vel pharetra. Aliquam etiam erat velit scelerisque in dictum.`,
      `FR4: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tincidunt id aliquet risus feugiat in ante metus. Vulputate eu scelerisque felis imperdiet proin. Blandit volutpat maecenas volutpat blandit aliquam etiam erat. Arcu non odio euismod lacinia. Rutrum quisque non tellus orci ac auctor. Aenean sed adipiscing diam donec adipiscing. Tristique magna sit amet purus gravida quis blandit turpis cursus. Orci porta non pulvinar neque laoreet suspendisse interdum. Sed odio morbi quis commodo odio aenean. Volutpat est velit egestas dui id ornare arcu. Diam vulputate ut pharetra sit. Diam quam nulla porttitor massa id neque. Vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Quis enim lobortis scelerisque fermentum dui faucibus. Eget arcu dictum varius duis at consectetur lorem donec. Tempor id eu nisl nunc mi ipsum faucibus vitae aliquet. Eget velit aliquet sagittis id. Auctor elit sed vulputate mi sit. Risus commodo viverra maecenas accumsan.

    Et magnis dis parturient montes. Accumsan in nisl nisi scelerisque eu ultrices vitae auctor. Odio eu feugiat pretium nibh ipsum. Libero id faucibus nisl tincidunt eget nullam. Viverra nam libero justo laoreet sit amet cursus sit. Vel quam elementum pulvinar etiam. Bibendum neque egestas congue quisque egestas diam in. Purus in massa tempor nec. Ante metus dictum at tempor commodo ullamcorper a lacus. Nunc eget lorem dolor sed viverra ipsum nunc. Lectus urna duis convallis convallis. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Amet volutpat consequat mauris nunc congue nisi vitae. Tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus. Sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus. Sit amet volutpat consequat mauris nunc congue nisi. Sit amet venenatis urna cursus eget nunc. Sagittis nisl rhoncus mattis rhoncus urna neque viverra justo.
    
    Quis risus sed vulputate odio ut enim blandit volutpat maecenas. Eget mi proin sed libero enim sed faucibus. Sed euismod nisi porta lorem mollis aliquam. Suspendisse faucibus interdum posuere lorem ipsum. Aliquam ut porttitor leo a diam sollicitudin. Nibh venenatis cras sed felis eget. Neque laoreet suspendisse interdum consectetur libero id faucibus nisl tincidunt. Quam id leo in vitae turpis massa sed elementum. Magna eget est lorem ipsum dolor. Eu augue ut lectus arcu bibendum at varius. Lectus vestibulum mattis ullamcorper velit. Sed libero enim sed faucibus turpis in eu. Sed cras ornare arcu dui vivamus arcu felis bibendum. Amet dictum sit amet justo. Tempus urna et pharetra pharetra. A scelerisque purus semper eget duis at tellus at urna.
    
    Mattis molestie a iaculis at erat pellentesque adipiscing commodo. Vel risus commodo viverra maecenas accumsan lacus vel facilisis volutpat. Sagittis vitae et leo duis ut diam quam nulla porttitor. Egestas egestas fringilla phasellus faucibus scelerisque eleifend donec. Iaculis urna id volutpat lacus. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Nunc faucibus a pellentesque sit amet porttitor eget dolor. Eget mauris pharetra et ultrices neque ornare aenean. Dui ut ornare lectus sit. Ac feugiat sed lectus vestibulum mattis ullamcorper velit sed. Faucibus ornare suspendisse sed nisi lacus sed viverra. Arcu dui vivamus arcu felis bibendum ut tristique. Amet commodo nulla facilisi nullam vehicula ipsum a arcu. Convallis aenean et tortor at risus. Elementum nibh tellus molestie nunc non. Interdum posuere lorem ipsum dolor sit. Varius duis at consectetur lorem donec massa sapien faucibus.
    
    Congue nisi vitae suscipit tellus mauris a diam maecenas. A erat nam at lectus. Eget egestas purus viverra accumsan in. Ac auctor augue mauris augue neque gravida. Sed viverra ipsum nunc aliquet bibendum enim. Proin libero nunc consequat interdum varius sit. Dictumst quisque sagittis purus sit. Bibendum arcu vitae elementum curabitur. In hac habitasse platea dictumst. Accumsan tortor posuere ac ut consequat semper viverra nam libero. Mauris in aliquam sem fringilla ut morbi tincidunt. Vel eros donec ac odio. Enim ut sem viverra aliquet. Scelerisque viverra mauris in aliquam sem fringilla ut. Arcu bibendum at varius vel pharetra. Aliquam etiam erat velit scelerisque in dictum.`,
    ],
  },
  pl: {
    name: "Polish",
    texts: [
      `PL1: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tincidunt id aliquet risus feugiat in ante metus. Vulputate eu scelerisque felis imperdiet proin. Blandit volutpat maecenas volutpat blandit aliquam etiam erat. Arcu non odio euismod lacinia. Rutrum quisque non tellus orci ac auctor. Aenean sed adipiscing diam donec adipiscing. Tristique magna sit amet purus gravida quis blandit turpis cursus. Orci porta non pulvinar neque laoreet suspendisse interdum. Sed odio morbi quis commodo odio aenean. Volutpat est velit egestas dui id ornare arcu. Diam vulputate ut pharetra sit. Diam quam nulla porttitor massa id neque. Vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Quis enim lobortis scelerisque fermentum dui faucibus. Eget arcu dictum varius duis at consectetur lorem donec. Tempor id eu nisl nunc mi ipsum faucibus vitae aliquet. Eget velit aliquet sagittis id. Auctor elit sed vulputate mi sit. Risus commodo viverra maecenas accumsan.

    Et magnis dis parturient montes. Accumsan in nisl nisi scelerisque eu ultrices vitae auctor. Odio eu feugiat pretium nibh ipsum. Libero id faucibus nisl tincidunt eget nullam. Viverra nam libero justo laoreet sit amet cursus sit. Vel quam elementum pulvinar etiam. Bibendum neque egestas congue quisque egestas diam in. Purus in massa tempor nec. Ante metus dictum at tempor commodo ullamcorper a lacus. Nunc eget lorem dolor sed viverra ipsum nunc. Lectus urna duis convallis convallis. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Amet volutpat consequat mauris nunc congue nisi vitae. Tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus. Sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus. Sit amet volutpat consequat mauris nunc congue nisi. Sit amet venenatis urna cursus eget nunc. Sagittis nisl rhoncus mattis rhoncus urna neque viverra justo.

    Quis risus sed vulputate odio ut enim blandit volutpat maecenas. Eget mi proin sed libero enim sed faucibus. Sed euismod nisi porta lorem mollis aliquam. Suspendisse faucibus interdum posuere lorem ipsum. Aliquam ut porttitor leo a diam sollicitudin. Nibh venenatis cras sed felis eget. Neque laoreet suspendisse interdum consectetur libero id faucibus nisl tincidunt. Quam id leo in vitae turpis massa sed elementum. Magna eget est lorem ipsum dolor. Eu augue ut lectus arcu bibendum at varius. Lectus vestibulum mattis ullamcorper velit. Sed libero enim sed faucibus turpis in eu. Sed cras ornare arcu dui vivamus arcu felis bibendum. Amet dictum sit amet justo. Tempus urna et pharetra pharetra. A scelerisque purus semper eget duis at tellus at urna.

    Mattis molestie a iaculis at erat pellentesque adipiscing commodo. Vel risus commodo viverra maecenas accumsan lacus vel facilisis volutpat. Sagittis vitae et leo duis ut diam quam nulla porttitor. Egestas egestas fringilla phasellus faucibus scelerisque eleifend donec. Iaculis urna id volutpat lacus. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Nunc faucibus a pellentesque sit amet porttitor eget dolor. Eget mauris pharetra et ultrices neque ornare aenean. Dui ut ornare lectus sit. Ac feugiat sed lectus vestibulum mattis ullamcorper velit sed. Faucibus ornare suspendisse sed nisi lacus sed viverra. Arcu dui vivamus arcu felis bibendum ut tristique. Amet commodo nulla facilisi nullam vehicula ipsum a arcu. Convallis aenean et tortor at risus. Elementum nibh tellus molestie nunc non. Interdum posuere lorem ipsum dolor sit. Varius duis at consectetur lorem donec massa sapien faucibus.

    Congue nisi vitae suscipit tellus mauris a diam maecenas. A erat nam at lectus. Eget egestas purus viverra accumsan in. Ac auctor augue mauris augue neque gravida. Sed viverra ipsum nunc aliquet bibendum enim. Proin libero nunc consequat interdum varius sit. Dictumst quisque sagittis purus sit. Bibendum arcu vitae elementum curabitur. In hac habitasse platea dictumst. Accumsan tortor posuere ac ut consequat semper viverra nam libero. Mauris in aliquam sem fringilla ut morbi tincidunt. Vel eros donec ac odio. Enim ut sem viverra aliquet. Scelerisque viverra mauris in aliquam sem fringilla ut. Arcu bibendum at varius vel pharetra. Aliquam etiam erat velit scelerisque in dictum.`,

      `PL2: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tincidunt id aliquet risus feugiat in ante metus. Vulputate eu scelerisque felis imperdiet proin. Blandit volutpat maecenas volutpat blandit aliquam etiam erat. Arcu non odio euismod lacinia. Rutrum quisque non tellus orci ac auctor. Aenean sed adipiscing diam donec adipiscing. Tristique magna sit amet purus gravida quis blandit turpis cursus. Orci porta non pulvinar neque laoreet suspendisse interdum. Sed odio morbi quis commodo odio aenean. Volutpat est velit egestas dui id ornare arcu. Diam vulputate ut pharetra sit. Diam quam nulla porttitor massa id neque. Vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Quis enim lobortis scelerisque fermentum dui faucibus. Eget arcu dictum varius duis at consectetur lorem donec. Tempor id eu nisl nunc mi ipsum faucibus vitae aliquet. Eget velit aliquet sagittis id. Auctor elit sed vulputate mi sit. Risus commodo viverra maecenas accumsan.

    Et magnis dis parturient montes. Accumsan in nisl nisi scelerisque eu ultrices vitae auctor. Odio eu feugiat pretium nibh ipsum. Libero id faucibus nisl tincidunt eget nullam. Viverra nam libero justo laoreet sit amet cursus sit. Vel quam elementum pulvinar etiam. Bibendum neque egestas congue quisque egestas diam in. Purus in massa tempor nec. Ante metus dictum at tempor commodo ullamcorper a lacus. Nunc eget lorem dolor sed viverra ipsum nunc. Lectus urna duis convallis convallis. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Amet volutpat consequat mauris nunc congue nisi vitae. Tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus. Sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus. Sit amet volutpat consequat mauris nunc congue nisi. Sit amet venenatis urna cursus eget nunc. Sagittis nisl rhoncus mattis rhoncus urna neque viverra justo.
    
    Quis risus sed vulputate odio ut enim blandit volutpat maecenas. Eget mi proin sed libero enim sed faucibus. Sed euismod nisi porta lorem mollis aliquam. Suspendisse faucibus interdum posuere lorem ipsum. Aliquam ut porttitor leo a diam sollicitudin. Nibh venenatis cras sed felis eget. Neque laoreet suspendisse interdum consectetur libero id faucibus nisl tincidunt. Quam id leo in vitae turpis massa sed elementum. Magna eget est lorem ipsum dolor. Eu augue ut lectus arcu bibendum at varius. Lectus vestibulum mattis ullamcorper velit. Sed libero enim sed faucibus turpis in eu. Sed cras ornare arcu dui vivamus arcu felis bibendum. Amet dictum sit amet justo. Tempus urna et pharetra pharetra. A scelerisque purus semper eget duis at tellus at urna.
    
    Mattis molestie a iaculis at erat pellentesque adipiscing commodo. Vel risus commodo viverra maecenas accumsan lacus vel facilisis volutpat. Sagittis vitae et leo duis ut diam quam nulla porttitor. Egestas egestas fringilla phasellus faucibus scelerisque eleifend donec. Iaculis urna id volutpat lacus. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Nunc faucibus a pellentesque sit amet porttitor eget dolor. Eget mauris pharetra et ultrices neque ornare aenean. Dui ut ornare lectus sit. Ac feugiat sed lectus vestibulum mattis ullamcorper velit sed. Faucibus ornare suspendisse sed nisi lacus sed viverra. Arcu dui vivamus arcu felis bibendum ut tristique. Amet commodo nulla facilisi nullam vehicula ipsum a arcu. Convallis aenean et tortor at risus. Elementum nibh tellus molestie nunc non. Interdum posuere lorem ipsum dolor sit. Varius duis at consectetur lorem donec massa sapien faucibus.
    
    Congue nisi vitae suscipit tellus mauris a diam maecenas. A erat nam at lectus. Eget egestas purus viverra accumsan in. Ac auctor augue mauris augue neque gravida. Sed viverra ipsum nunc aliquet bibendum enim. Proin libero nunc consequat interdum varius sit. Dictumst quisque sagittis purus sit. Bibendum arcu vitae elementum curabitur. In hac habitasse platea dictumst. Accumsan tortor posuere ac ut consequat semper viverra nam libero. Mauris in aliquam sem fringilla ut morbi tincidunt. Vel eros donec ac odio. Enim ut sem viverra aliquet. Scelerisque viverra mauris in aliquam sem fringilla ut. Arcu bibendum at varius vel pharetra. Aliquam etiam erat velit scelerisque in dictum.`,
      `PL3: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tincidunt id aliquet risus feugiat in ante metus. Vulputate eu scelerisque felis imperdiet proin. Blandit volutpat maecenas volutpat blandit aliquam etiam erat. Arcu non odio euismod lacinia. Rutrum quisque non tellus orci ac auctor. Aenean sed adipiscing diam donec adipiscing. Tristique magna sit amet purus gravida quis blandit turpis cursus. Orci porta non pulvinar neque laoreet suspendisse interdum. Sed odio morbi quis commodo odio aenean. Volutpat est velit egestas dui id ornare arcu. Diam vulputate ut pharetra sit. Diam quam nulla porttitor massa id neque. Vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Quis enim lobortis scelerisque fermentum dui faucibus. Eget arcu dictum varius duis at consectetur lorem donec. Tempor id eu nisl nunc mi ipsum faucibus vitae aliquet. Eget velit aliquet sagittis id. Auctor elit sed vulputate mi sit. Risus commodo viverra maecenas accumsan.

    Et magnis dis parturient montes. Accumsan in nisl nisi scelerisque eu ultrices vitae auctor. Odio eu feugiat pretium nibh ipsum. Libero id faucibus nisl tincidunt eget nullam. Viverra nam libero justo laoreet sit amet cursus sit. Vel quam elementum pulvinar etiam. Bibendum neque egestas congue quisque egestas diam in. Purus in massa tempor nec. Ante metus dictum at tempor commodo ullamcorper a lacus. Nunc eget lorem dolor sed viverra ipsum nunc. Lectus urna duis convallis convallis. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Amet volutpat consequat mauris nunc congue nisi vitae. Tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus. Sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus. Sit amet volutpat consequat mauris nunc congue nisi. Sit amet venenatis urna cursus eget nunc. Sagittis nisl rhoncus mattis rhoncus urna neque viverra justo.
    
    Quis risus sed vulputate odio ut enim blandit volutpat maecenas. Eget mi proin sed libero enim sed faucibus. Sed euismod nisi porta lorem mollis aliquam. Suspendisse faucibus interdum posuere lorem ipsum. Aliquam ut porttitor leo a diam sollicitudin. Nibh venenatis cras sed felis eget. Neque laoreet suspendisse interdum consectetur libero id faucibus nisl tincidunt. Quam id leo in vitae turpis massa sed elementum. Magna eget est lorem ipsum dolor. Eu augue ut lectus arcu bibendum at varius. Lectus vestibulum mattis ullamcorper velit. Sed libero enim sed faucibus turpis in eu. Sed cras ornare arcu dui vivamus arcu felis bibendum. Amet dictum sit amet justo. Tempus urna et pharetra pharetra. A scelerisque purus semper eget duis at tellus at urna.
    
    Mattis molestie a iaculis at erat pellentesque adipiscing commodo. Vel risus commodo viverra maecenas accumsan lacus vel facilisis volutpat. Sagittis vitae et leo duis ut diam quam nulla porttitor. Egestas egestas fringilla phasellus faucibus scelerisque eleifend donec. Iaculis urna id volutpat lacus. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Nunc faucibus a pellentesque sit amet porttitor eget dolor. Eget mauris pharetra et ultrices neque ornare aenean. Dui ut ornare lectus sit. Ac feugiat sed lectus vestibulum mattis ullamcorper velit sed. Faucibus ornare suspendisse sed nisi lacus sed viverra. Arcu dui vivamus arcu felis bibendum ut tristique. Amet commodo nulla facilisi nullam vehicula ipsum a arcu. Convallis aenean et tortor at risus. Elementum nibh tellus molestie nunc non. Interdum posuere lorem ipsum dolor sit. Varius duis at consectetur lorem donec massa sapien faucibus.
    
    Congue nisi vitae suscipit tellus mauris a diam maecenas. A erat nam at lectus. Eget egestas purus viverra accumsan in. Ac auctor augue mauris augue neque gravida. Sed viverra ipsum nunc aliquet bibendum enim. Proin libero nunc consequat interdum varius sit. Dictumst quisque sagittis purus sit. Bibendum arcu vitae elementum curabitur. In hac habitasse platea dictumst. Accumsan tortor posuere ac ut consequat semper viverra nam libero. Mauris in aliquam sem fringilla ut morbi tincidunt. Vel eros donec ac odio. Enim ut sem viverra aliquet. Scelerisque viverra mauris in aliquam sem fringilla ut. Arcu bibendum at varius vel pharetra. Aliquam etiam erat velit scelerisque in dictum.`,
      `PL4: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tincidunt id aliquet risus feugiat in ante metus. Vulputate eu scelerisque felis imperdiet proin. Blandit volutpat maecenas volutpat blandit aliquam etiam erat. Arcu non odio euismod lacinia. Rutrum quisque non tellus orci ac auctor. Aenean sed adipiscing diam donec adipiscing. Tristique magna sit amet purus gravida quis blandit turpis cursus. Orci porta non pulvinar neque laoreet suspendisse interdum. Sed odio morbi quis commodo odio aenean. Volutpat est velit egestas dui id ornare arcu. Diam vulputate ut pharetra sit. Diam quam nulla porttitor massa id neque. Vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Quis enim lobortis scelerisque fermentum dui faucibus. Eget arcu dictum varius duis at consectetur lorem donec. Tempor id eu nisl nunc mi ipsum faucibus vitae aliquet. Eget velit aliquet sagittis id. Auctor elit sed vulputate mi sit. Risus commodo viverra maecenas accumsan.

    Et magnis dis parturient montes. Accumsan in nisl nisi scelerisque eu ultrices vitae auctor. Odio eu feugiat pretium nibh ipsum. Libero id faucibus nisl tincidunt eget nullam. Viverra nam libero justo laoreet sit amet cursus sit. Vel quam elementum pulvinar etiam. Bibendum neque egestas congue quisque egestas diam in. Purus in massa tempor nec. Ante metus dictum at tempor commodo ullamcorper a lacus. Nunc eget lorem dolor sed viverra ipsum nunc. Lectus urna duis convallis convallis. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Amet volutpat consequat mauris nunc congue nisi vitae. Tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus. Sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus. Sit amet volutpat consequat mauris nunc congue nisi. Sit amet venenatis urna cursus eget nunc. Sagittis nisl rhoncus mattis rhoncus urna neque viverra justo.
    
    Quis risus sed vulputate odio ut enim blandit volutpat maecenas. Eget mi proin sed libero enim sed faucibus. Sed euismod nisi porta lorem mollis aliquam. Suspendisse faucibus interdum posuere lorem ipsum. Aliquam ut porttitor leo a diam sollicitudin. Nibh venenatis cras sed felis eget. Neque laoreet suspendisse interdum consectetur libero id faucibus nisl tincidunt. Quam id leo in vitae turpis massa sed elementum. Magna eget est lorem ipsum dolor. Eu augue ut lectus arcu bibendum at varius. Lectus vestibulum mattis ullamcorper velit. Sed libero enim sed faucibus turpis in eu. Sed cras ornare arcu dui vivamus arcu felis bibendum. Amet dictum sit amet justo. Tempus urna et pharetra pharetra. A scelerisque purus semper eget duis at tellus at urna.
    
    Mattis molestie a iaculis at erat pellentesque adipiscing commodo. Vel risus commodo viverra maecenas accumsan lacus vel facilisis volutpat. Sagittis vitae et leo duis ut diam quam nulla porttitor. Egestas egestas fringilla phasellus faucibus scelerisque eleifend donec. Iaculis urna id volutpat lacus. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Nunc faucibus a pellentesque sit amet porttitor eget dolor. Eget mauris pharetra et ultrices neque ornare aenean. Dui ut ornare lectus sit. Ac feugiat sed lectus vestibulum mattis ullamcorper velit sed. Faucibus ornare suspendisse sed nisi lacus sed viverra. Arcu dui vivamus arcu felis bibendum ut tristique. Amet commodo nulla facilisi nullam vehicula ipsum a arcu. Convallis aenean et tortor at risus. Elementum nibh tellus molestie nunc non. Interdum posuere lorem ipsum dolor sit. Varius duis at consectetur lorem donec massa sapien faucibus.
    
    Congue nisi vitae suscipit tellus mauris a diam maecenas. A erat nam at lectus. Eget egestas purus viverra accumsan in. Ac auctor augue mauris augue neque gravida. Sed viverra ipsum nunc aliquet bibendum enim. Proin libero nunc consequat interdum varius sit. Dictumst quisque sagittis purus sit. Bibendum arcu vitae elementum curabitur. In hac habitasse platea dictumst. Accumsan tortor posuere ac ut consequat semper viverra nam libero. Mauris in aliquam sem fringilla ut morbi tincidunt. Vel eros donec ac odio. Enim ut sem viverra aliquet. Scelerisque viverra mauris in aliquam sem fringilla ut. Arcu bibendum at varius vel pharetra. Aliquam etiam erat velit scelerisque in dictum.`,
    ],
  },
};

export default languages;
